### ISSUE TITLE
CHANMODES of development server (claims version aspircd 5.0.9-devel) shows eIbqU; quiet mode is really y; U is chm_nosuch; add prefix for ownerbot

### ISSUE THREAD

**Issue by janicez** [hyphovy/aspIRCd#12]
A mode can't be both a LIST mode and a PREFIX mode. Which is it?

Is it q? Is it y? Is it a forced tremor?

**Comment by TwinUsers** [comment]
He's learning Jack, not everyone is a epic coder like you. 😁

**Comment by badccv** [comment]
Hi @janicez , Fixed!
